# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# User.create(username: 'joshsea')
User.create(username: 'tom')
User.create(username: 'jerry')

c1 = Classroom.create(name: 'Bio 101')
c2 = Classroom.create(name: 'Math 101')
c3 = Classroom.create(name: 'English 101')

Note.create(title:"Test Note 1", content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus volutpat justo sed est tincidunt accumsan. Nam eget quam urna. Praesent lacinia odio metus, a venenatis orci porta sed. Mauris rutrum justo sit amet sem commodo faucibus. Suspendisse egestas eget est in posuere. Duis ac elit sed felis fringilla elementum. Ut a diam at arcu maximus iaculis. Nam placerat ante eu suscipit placerat. Vivamus cursus purus ipsum, ut facilisis lectus ullamcorper ac. Proin eget turpis non ligula placerat fringilla id a ante.

Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris scelerisque maximus dui, in rutrum magna mollis eget. Vivamus at massa at dolor feugiat rutrum. Pellentesque vel neque accumsan, rutrum nulla in, facilisis lectus. Cras eleifend odio quam, a pellentesque nisi auctor quis. Nulla luctus pellentesque turpis, non volutpat felis accumsan ac. Ut at quam non purus finibus sodales nec non arcu. Vivamus sed sagittis eros. Etiam imperdiet erat eget lacus placerat, in mattis mauris hendrerit. Aliquam vitae feugiat magna, nec semper urna. Proin porttitor sagittis libero in placerat. Fusce mauris tellus, cursus et risus ut, venenatis rutrum orci. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus maximus nisl tortor, ac blandit tellus molestie eu. Mauris volutpat laoreet eros non tempus.

Nulla vitae ante vel urna cursus aliquet. Curabitur semper volutpat lobortis. Fusce et turpis eu quam gravida tempus a nec tortor. Mauris in semper elit. Maecenas congue diam mollis dolor luctus ultrices. Duis sed porttitor nunc, ut venenatis tortor. Praesent dictum lorem quis justo porttitor, quis iaculis turpis consequat. Donec vitae convallis ligula. Fusce laoreet lectus id nibh egestas, sit amet commodo nibh bibendum. Sed tempus velit vitae diam efficitur dapibus. Fusce eu nisi enim. Praesent vehicula fringilla tincidunt.

Donec et rhoncus sapien. Etiam ligula quam, rhoncus eu fermentum nec, pharetra a libero. Phasellus fringilla, augue et gravida molestie, urna erat congue nulla, nec suscipit nibh dui ac massa. In tincidunt suscipit purus. Sed sit amet ipsum sit amet tortor rhoncus pretium. Suspendisse et arcu semper, ullamcorper urna vitae, lacinia ligula. Suspendisse consequat in neque vitae malesuada. Pellentesque ut tristique quam. Nunc eu erat odio. Aenean erat erat, vehicula non consequat eget, tincidunt quis mi.

Nam commodo condimentum metus. Ut rutrum vulputate imperdiet. In eu sem eget libero semper consequat. Mauris accumsan nunc ut turpis feugiat dapibus. Sed aliquam purus volutpat tempor accumsan. Suspendisse placerat a metus quis laoreet. Suspendisse tristique interdum tortor et lacinia. In eu nisi quis arcu egestas ultricies eget sit amet magna. Morbi imperdiet et leo eget pharetra. Quisque hendrerit porta lacus sed eleifend. Quisque non fermentum nulla, sed gravida lacus. Donec pretium justo sit amet neque porttitor scelerisque. Mauris cursus pulvinar mi vitae cursus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos ', user_id: User.first.id, classroom_id: 1)
Note.create(title:"Test Note 2", content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus volutpat justo sed est tincidunt accumsan. Nam eget quam urna. Praesent lacinia odio metus, a venenatis orci porta sed. Mauris rutrum justo sit amet sem commodo faucibus. Suspendisse egestas eget est in posuere. Duis ac elit sed felis fringilla elementum. Ut a diam at arcu maximus iaculis. Nam placerat ante eu suscipit placerat. Vivamus cursus purus ipsum, ut facilisis lectus ullamcorper ac. Proin eget turpis non ligula placerat fringilla id a ante.

Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris scelerisque maximus dui, in rutrum magna mollis eget. Vivamus at massa at dolor feugiat rutrum. Pellentesque vel neque accumsan, rutrum nulla in, facilisis lectus. Cras eleifend odio quam, a pellentesque nisi auctor quis. Nulla luctus pellentesque turpis, non volutpat felis accumsan ac. Ut at quam non purus finibus sodales nec non arcu. Vivamus sed sagittis eros. Etiam imperdiet erat eget lacus placerat, in mattis mauris hendrerit. Aliquam vitae feugiat magna, nec semper urna. Proin porttitor sagittis libero in placerat. Fusce mauris tellus, cursus et risus ut, venenatis rutrum orci. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus maximus nisl tortor, ac blandit tellus molestie eu. Mauris volutpat laoreet eros non tempus.

Nulla vitae ante vel urna cursus aliquet. Curabitur semper volutpat lobortis. Fusce et turpis eu quam gravida tempus a nec tortor. Mauris in semper elit. Maecenas congue diam mollis dolor luctus ultrices. Duis sed porttitor nunc, ut venenatis tortor. Praesent dictum lorem quis justo porttitor, quis iaculis turpis consequat. Donec vitae convallis ligula. Fusce laoreet lectus id nibh egestas, sit amet commodo nibh bibendum. Sed tempus velit vitae diam efficitur dapibus. Fusce eu nisi enim. Praesent vehicula fringilla tincidunt.

Donec et rhoncus sapien. Etiam ligula quam, rhoncus eu fermentum nec, pharetra a libero. Phasellus fringilla, augue et gravida molestie, urna erat congue nulla, nec suscipit nibh dui ac massa. In tincidunt suscipit purus. Sed sit amet ipsum sit amet tortor rhoncus pretium. Suspendisse et arcu semper, ullamcorper urna vitae, lacinia ligula. Suspendisse consequat in neque vitae malesuada. Pellentesque ut tristique quam. Nunc eu erat odio. Aenean erat erat, vehicula non consequat eget, tincidunt quis mi.

Nam commodo condimentum metus. Ut rutrum vulputate imperdiet. In eu sem eget libero semper consequat. Mauris accumsan nunc ut turpis feugiat dapibus. Sed aliquam purus volutpat tempor accumsan. Suspendisse placerat a metus quis laoreet. Suspendisse tristique interdum tortor et lacinia. In eu nisi quis arcu egestas ultricies eget sit amet magna. Morbi imperdiet et leo eget pharetra. Quisque hendrerit porta lacus sed eleifend. Quisque non fermentum nulla, sed gravida lacus. Donec pretium justo sit amet neque porttitor scelerisque. Mauris cursus pulvinar mi vitae cursus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos ', user_id: User.first.id, classroom_id: 1)
Note.create(title:"Test Note 3", content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus volutpat justo sed est tincidunt accumsan. Nam eget quam urna. Praesent lacinia odio metus, a venenatis orci porta sed. Mauris rutrum justo sit amet sem commodo faucibus. Suspendisse egestas eget est in posuere. Duis ac elit sed felis fringilla elementum. Ut a diam at arcu maximus iaculis. Nam placerat ante eu suscipit placerat. Vivamus cursus purus ipsum, ut facilisis lectus ullamcorper ac. Proin eget turpis non ligula placerat fringilla id a ante.

Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris scelerisque maximus dui, in rutrum magna mollis eget. Vivamus at massa at dolor feugiat rutrum. Pellentesque vel neque accumsan, rutrum nulla in, facilisis lectus. Cras eleifend odio quam, a pellentesque nisi auctor quis. Nulla luctus pellentesque turpis, non volutpat felis accumsan ac. Ut at quam non purus finibus sodales nec non arcu. Vivamus sed sagittis eros. Etiam imperdiet erat eget lacus placerat, in mattis mauris hendrerit. Aliquam vitae feugiat magna, nec semper urna. Proin porttitor sagittis libero in placerat. Fusce mauris tellus, cursus et risus ut, venenatis rutrum orci. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus maximus nisl tortor, ac blandit tellus molestie eu. Mauris volutpat laoreet eros non tempus.

Nulla vitae ante vel urna cursus aliquet. Curabitur semper volutpat lobortis. Fusce et turpis eu quam gravida tempus a nec tortor. Mauris in semper elit. Maecenas congue diam mollis dolor luctus ultrices. Duis sed porttitor nunc, ut venenatis tortor. Praesent dictum lorem quis justo porttitor, quis iaculis turpis consequat. Donec vitae convallis ligula. Fusce laoreet lectus id nibh egestas, sit amet commodo nibh bibendum. Sed tempus velit vitae diam efficitur dapibus. Fusce eu nisi enim. Praesent vehicula fringilla tincidunt.

Donec et rhoncus sapien. Etiam ligula quam, rhoncus eu fermentum nec, pharetra a libero. Phasellus fringilla, augue et gravida molestie, urna erat congue nulla, nec suscipit nibh dui ac massa. In tincidunt suscipit purus. Sed sit amet ipsum sit amet tortor rhoncus pretium. Suspendisse et arcu semper, ullamcorper urna vitae, lacinia ligula. Suspendisse consequat in neque vitae malesuada. Pellentesque ut tristique quam. Nunc eu erat odio. Aenean erat erat, vehicula non consequat eget, tincidunt quis mi.

Nam commodo condimentum metus. Ut rutrum vulputate imperdiet. In eu sem eget libero semper consequat. Mauris accumsan nunc ut turpis feugiat dapibus. Sed aliquam purus volutpat tempor accumsan. Suspendisse placerat a metus quis laoreet. Suspendisse tristique interdum tortor et lacinia. In eu nisi quis arcu egestas ultricies eget sit amet magna. Morbi imperdiet et leo eget pharetra. Quisque hendrerit porta lacus sed eleifend. Quisque non fermentum nulla, sed gravida lacus. Donec pretium justo sit amet neque porttitor scelerisque. Mauris cursus pulvinar mi vitae cursus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos ', user_id: User.first.id, classroom_id: 1)
Note.create(title:"Test Note 4", content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus volutpat justo sed est tincidunt accumsan. Nam eget quam urna. Praesent lacinia odio metus, a venenatis orci porta sed. Mauris rutrum justo sit amet sem commodo faucibus. Suspendisse egestas eget est in posuere. Duis ac elit sed felis fringilla elementum. Ut a diam at arcu maximus iaculis. Nam placerat ante eu suscipit placerat. Vivamus cursus purus ipsum, ut facilisis lectus ullamcorper ac. Proin eget turpis non ligula placerat fringilla id a ante.

Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris scelerisque maximus dui, in rutrum magna mollis eget. Vivamus at massa at dolor feugiat rutrum. Pellentesque vel neque accumsan, rutrum nulla in, facilisis lectus. Cras eleifend odio quam, a pellentesque nisi auctor quis. Nulla luctus pellentesque turpis, non volutpat felis accumsan ac. Ut at quam non purus finibus sodales nec non arcu. Vivamus sed sagittis eros. Etiam imperdiet erat eget lacus placerat, in mattis mauris hendrerit. Aliquam vitae feugiat magna, nec semper urna. Proin porttitor sagittis libero in placerat. Fusce mauris tellus, cursus et risus ut, venenatis rutrum orci. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus maximus nisl tortor, ac blandit tellus molestie eu. Mauris volutpat laoreet eros non tempus.

Nulla vitae ante vel urna cursus aliquet. Curabitur semper volutpat lobortis. Fusce et turpis eu quam gravida tempus a nec tortor. Mauris in semper elit. Maecenas congue diam mollis dolor luctus ultrices. Duis sed porttitor nunc, ut venenatis tortor. Praesent dictum lorem quis justo porttitor, quis iaculis turpis consequat. Donec vitae convallis ligula. Fusce laoreet lectus id nibh egestas, sit amet commodo nibh bibendum. Sed tempus velit vitae diam efficitur dapibus. Fusce eu nisi enim. Praesent vehicula fringilla tincidunt.

Donec et rhoncus sapien. Etiam ligula quam, rhoncus eu fermentum nec, pharetra a libero. Phasellus fringilla, augue et gravida molestie, urna erat congue nulla, nec suscipit nibh dui ac massa. In tincidunt suscipit purus. Sed sit amet ipsum sit amet tortor rhoncus pretium. Suspendisse et arcu semper, ullamcorper urna vitae, lacinia ligula. Suspendisse consequat in neque vitae malesuada. Pellentesque ut tristique quam. Nunc eu erat odio. Aenean erat erat, vehicula non consequat eget, tincidunt quis mi.

Nam commodo condimentum metus. Ut rutrum vulputate imperdiet. In eu sem eget libero semper consequat. Mauris accumsan nunc ut turpis feugiat dapibus. Sed aliquam purus volutpat tempor accumsan. Suspendisse placerat a metus quis laoreet. Suspendisse tristique interdum tortor et lacinia. In eu nisi quis arcu egestas ultricies eget sit amet magna. Morbi imperdiet et leo eget pharetra. Quisque hendrerit porta lacus sed eleifend. Quisque non fermentum nulla, sed gravida lacus. Donec pretium justo sit amet neque porttitor scelerisque. Mauris cursus pulvinar mi vitae cursus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos ', user_id: User.first.id, classroom_id: 1)

Note.create(title:"Test Note 5", content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus volutpat justo sed est tincidunt accumsan. Nam eget quam urna. Praesent lacinia odio metus, a venenatis orci porta sed. Mauris rutrum justo sit amet sem commodo faucibus. Suspendisse egestas eget est in posuere. Duis ac elit sed felis fringilla elementum. Ut a diam at arcu maximus iaculis. Nam placerat ante eu suscipit placerat. Vivamus cursus purus ipsum, ut facilisis lectus ullamcorper ac. Proin eget turpis non ligula placerat fringilla id a ante.

Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris scelerisque maximus dui, in rutrum magna mollis eget. Vivamus at massa at dolor feugiat rutrum. Pellentesque vel neque accumsan, rutrum nulla in, facilisis lectus. Cras eleifend odio quam, a pellentesque nisi auctor quis. Nulla luctus pellentesque turpis, non volutpat felis accumsan ac. Ut at quam non purus finibus sodales nec non arcu. Vivamus sed sagittis eros. Etiam imperdiet erat eget lacus placerat, in mattis mauris hendrerit. Aliquam vitae feugiat magna, nec semper urna. Proin porttitor sagittis libero in placerat. Fusce mauris tellus, cursus et risus ut, venenatis rutrum orci. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus maximus nisl tortor, ac blandit tellus molestie eu. Mauris volutpat laoreet eros non tempus.

Nulla vitae ante vel urna cursus aliquet. Curabitur semper volutpat lobortis. Fusce et turpis eu quam gravida tempus a nec tortor. Mauris in semper elit. Maecenas congue diam mollis dolor luctus ultrices. Duis sed porttitor nunc, ut venenatis tortor. Praesent dictum lorem quis justo porttitor, quis iaculis turpis consequat. Donec vitae convallis ligula. Fusce laoreet lectus id nibh egestas, sit amet commodo nibh bibendum. Sed tempus velit vitae diam efficitur dapibus. Fusce eu nisi enim. Praesent vehicula fringilla tincidunt.

Donec et rhoncus sapien. Etiam ligula quam, rhoncus eu fermentum nec, pharetra a libero. Phasellus fringilla, augue et gravida molestie, urna erat congue nulla, nec suscipit nibh dui ac massa. In tincidunt suscipit purus. Sed sit amet ipsum sit amet tortor rhoncus pretium. Suspendisse et arcu semper, ullamcorper urna vitae, lacinia ligula. Suspendisse consequat in neque vitae malesuada. Pellentesque ut tristique quam. Nunc eu erat odio. Aenean erat erat, vehicula non consequat eget, tincidunt quis mi.

Nam commodo condimentum metus. Ut rutrum vulputate imperdiet. In eu sem eget libero semper consequat. Mauris accumsan nunc ut turpis feugiat dapibus. Sed aliquam purus volutpat tempor accumsan. Suspendisse placerat a metus quis laoreet. Suspendisse tristique interdum tortor et lacinia. In eu nisi quis arcu egestas ultricies eget sit amet magna. Morbi imperdiet et leo eget pharetra. Quisque hendrerit porta lacus sed eleifend. Quisque non fermentum nulla, sed gravida lacus. Donec pretium justo sit amet neque porttitor scelerisque. Mauris cursus pulvinar mi vitae cursus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos ', user_id: User.first.id, classroom_id: 2)
Note.create(title:"Test Note 6", content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus volutpat justo sed est tincidunt accumsan. Nam eget quam urna. Praesent lacinia odio metus, a venenatis orci porta sed. Mauris rutrum justo sit amet sem commodo faucibus. Suspendisse egestas eget est in posuere. Duis ac elit sed felis fringilla elementum. Ut a diam at arcu maximus iaculis. Nam placerat ante eu suscipit placerat. Vivamus cursus purus ipsum, ut facilisis lectus ullamcorper ac. Proin eget turpis non ligula placerat fringilla id a ante.

Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris scelerisque maximus dui, in rutrum magna mollis eget. Vivamus at massa at dolor feugiat rutrum. Pellentesque vel neque accumsan, rutrum nulla in, facilisis lectus. Cras eleifend odio quam, a pellentesque nisi auctor quis. Nulla luctus pellentesque turpis, non volutpat felis accumsan ac. Ut at quam non purus finibus sodales nec non arcu. Vivamus sed sagittis eros. Etiam imperdiet erat eget lacus placerat, in mattis mauris hendrerit. Aliquam vitae feugiat magna, nec semper urna. Proin porttitor sagittis libero in placerat. Fusce mauris tellus, cursus et risus ut, venenatis rutrum orci. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus maximus nisl tortor, ac blandit tellus molestie eu. Mauris volutpat laoreet eros non tempus.

Nulla vitae ante vel urna cursus aliquet. Curabitur semper volutpat lobortis. Fusce et turpis eu quam gravida tempus a nec tortor. Mauris in semper elit. Maecenas congue diam mollis dolor luctus ultrices. Duis sed porttitor nunc, ut venenatis tortor. Praesent dictum lorem quis justo porttitor, quis iaculis turpis consequat. Donec vitae convallis ligula. Fusce laoreet lectus id nibh egestas, sit amet commodo nibh bibendum. Sed tempus velit vitae diam efficitur dapibus. Fusce eu nisi enim. Praesent vehicula fringilla tincidunt.

Donec et rhoncus sapien. Etiam ligula quam, rhoncus eu fermentum nec, pharetra a libero. Phasellus fringilla, augue et gravida molestie, urna erat congue nulla, nec suscipit nibh dui ac massa. In tincidunt suscipit purus. Sed sit amet ipsum sit amet tortor rhoncus pretium. Suspendisse et arcu semper, ullamcorper urna vitae, lacinia ligula. Suspendisse consequat in neque vitae malesuada. Pellentesque ut tristique quam. Nunc eu erat odio. Aenean erat erat, vehicula non consequat eget, tincidunt quis mi.

Nam commodo condimentum metus. Ut rutrum vulputate imperdiet. In eu sem eget libero semper consequat. Mauris accumsan nunc ut turpis feugiat dapibus. Sed aliquam purus volutpat tempor accumsan. Suspendisse placerat a metus quis laoreet. Suspendisse tristique interdum tortor et lacinia. In eu nisi quis arcu egestas ultricies eget sit amet magna. Morbi imperdiet et leo eget pharetra. Quisque hendrerit porta lacus sed eleifend. Quisque non fermentum nulla, sed gravida lacus. Donec pretium justo sit amet neque porttitor scelerisque. Mauris cursus pulvinar mi vitae cursus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos ', user_id: User.first.id, classroom_id: 2)
Note.create(title:"Test Note 7", content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus volutpat justo sed est tincidunt accumsan. Nam eget quam urna. Praesent lacinia odio metus, a venenatis orci porta sed. Mauris rutrum justo sit amet sem commodo faucibus. Suspendisse egestas eget est in posuere. Duis ac elit sed felis fringilla elementum. Ut a diam at arcu maximus iaculis. Nam placerat ante eu suscipit placerat. Vivamus cursus purus ipsum, ut facilisis lectus ullamcorper ac. Proin eget turpis non ligula placerat fringilla id a ante.

Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris scelerisque maximus dui, in rutrum magna mollis eget. Vivamus at massa at dolor feugiat rutrum. Pellentesque vel neque accumsan, rutrum nulla in, facilisis lectus. Cras eleifend odio quam, a pellentesque nisi auctor quis. Nulla luctus pellentesque turpis, non volutpat felis accumsan ac. Ut at quam non purus finibus sodales nec non arcu. Vivamus sed sagittis eros. Etiam imperdiet erat eget lacus placerat, in mattis mauris hendrerit. Aliquam vitae feugiat magna, nec semper urna. Proin porttitor sagittis libero in placerat. Fusce mauris tellus, cursus et risus ut, venenatis rutrum orci. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus maximus nisl tortor, ac blandit tellus molestie eu. Mauris volutpat laoreet eros non tempus.

Nulla vitae ante vel urna cursus aliquet. Curabitur semper volutpat lobortis. Fusce et turpis eu quam gravida tempus a nec tortor. Mauris in semper elit. Maecenas congue diam mollis dolor luctus ultrices. Duis sed porttitor nunc, ut venenatis tortor. Praesent dictum lorem quis justo porttitor, quis iaculis turpis consequat. Donec vitae convallis ligula. Fusce laoreet lectus id nibh egestas, sit amet commodo nibh bibendum. Sed tempus velit vitae diam efficitur dapibus. Fusce eu nisi enim. Praesent vehicula fringilla tincidunt.

Donec et rhoncus sapien. Etiam ligula quam, rhoncus eu fermentum nec, pharetra a libero. Phasellus fringilla, augue et gravida molestie, urna erat congue nulla, nec suscipit nibh dui ac massa. In tincidunt suscipit purus. Sed sit amet ipsum sit amet tortor rhoncus pretium. Suspendisse et arcu semper, ullamcorper urna vitae, lacinia ligula. Suspendisse consequat in neque vitae malesuada. Pellentesque ut tristique quam. Nunc eu erat odio. Aenean erat erat, vehicula non consequat eget, tincidunt quis mi.

Nam commodo condimentum metus. Ut rutrum vulputate imperdiet. In eu sem eget libero semper consequat. Mauris accumsan nunc ut turpis feugiat dapibus. Sed aliquam purus volutpat tempor accumsan. Suspendisse placerat a metus quis laoreet. Suspendisse tristique interdum tortor et lacinia. In eu nisi quis arcu egestas ultricies eget sit amet magna. Morbi imperdiet et leo eget pharetra. Quisque hendrerit porta lacus sed eleifend. Quisque non fermentum nulla, sed gravida lacus. Donec pretium justo sit amet neque porttitor scelerisque. Mauris cursus pulvinar mi vitae cursus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos ', user_id: User.first.id, classroom_id: 2)
Note.create(title:"Test Note 8", content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus volutpat justo sed est tincidunt accumsan. Nam eget quam urna. Praesent lacinia odio metus, a venenatis orci porta sed. Mauris rutrum justo sit amet sem commodo faucibus. Suspendisse egestas eget est in posuere. Duis ac elit sed felis fringilla elementum. Ut a diam at arcu maximus iaculis. Nam placerat ante eu suscipit placerat. Vivamus cursus purus ipsum, ut facilisis lectus ullamcorper ac. Proin eget turpis non ligula placerat fringilla id a ante.

Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris scelerisque maximus dui, in rutrum magna mollis eget. Vivamus at massa at dolor feugiat rutrum. Pellentesque vel neque accumsan, rutrum nulla in, facilisis lectus. Cras eleifend odio quam, a pellentesque nisi auctor quis. Nulla luctus pellentesque turpis, non volutpat felis accumsan ac. Ut at quam non purus finibus sodales nec non arcu. Vivamus sed sagittis eros. Etiam imperdiet erat eget lacus placerat, in mattis mauris hendrerit. Aliquam vitae feugiat magna, nec semper urna. Proin porttitor sagittis libero in placerat. Fusce mauris tellus, cursus et risus ut, venenatis rutrum orci. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus maximus nisl tortor, ac blandit tellus molestie eu. Mauris volutpat laoreet eros non tempus.

Nulla vitae ante vel urna cursus aliquet. Curabitur semper volutpat lobortis. Fusce et turpis eu quam gravida tempus a nec tortor. Mauris in semper elit. Maecenas congue diam mollis dolor luctus ultrices. Duis sed porttitor nunc, ut venenatis tortor. Praesent dictum lorem quis justo porttitor, quis iaculis turpis consequat. Donec vitae convallis ligula. Fusce laoreet lectus id nibh egestas, sit amet commodo nibh bibendum. Sed tempus velit vitae diam efficitur dapibus. Fusce eu nisi enim. Praesent vehicula fringilla tincidunt.

Donec et rhoncus sapien. Etiam ligula quam, rhoncus eu fermentum nec, pharetra a libero. Phasellus fringilla, augue et gravida molestie, urna erat congue nulla, nec suscipit nibh dui ac massa. In tincidunt suscipit purus. Sed sit amet ipsum sit amet tortor rhoncus pretium. Suspendisse et arcu semper, ullamcorper urna vitae, lacinia ligula. Suspendisse consequat in neque vitae malesuada. Pellentesque ut tristique quam. Nunc eu erat odio. Aenean erat erat, vehicula non consequat eget, tincidunt quis mi.

Nam commodo condimentum metus. Ut rutrum vulputate imperdiet. In eu sem eget libero semper consequat. Mauris accumsan nunc ut turpis feugiat dapibus. Sed aliquam purus volutpat tempor accumsan. Suspendisse placerat a metus quis laoreet. Suspendisse tristique interdum tortor et lacinia. In eu nisi quis arcu egestas ultricies eget sit amet magna. Morbi imperdiet et leo eget pharetra. Quisque hendrerit porta lacus sed eleifend. Quisque non fermentum nulla, sed gravida lacus. Donec pretium justo sit amet neque porttitor scelerisque. Mauris cursus pulvinar mi vitae cursus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos ', user_id: User.first.id, classroom_id: 2)

Note.create(title:"Test Note 9", content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus volutpat justo sed est tincidunt accumsan. Nam eget quam urna. Praesent lacinia odio metus, a venenatis orci porta sed. Mauris rutrum justo sit amet sem commodo faucibus. Suspendisse egestas eget est in posuere. Duis ac elit sed felis fringilla elementum. Ut a diam at arcu maximus iaculis. Nam placerat ante eu suscipit placerat. Vivamus cursus purus ipsum, ut facilisis lectus ullamcorper ac. Proin eget turpis non ligula placerat fringilla id a ante.

Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris scelerisque maximus dui, in rutrum magna mollis eget. Vivamus at massa at dolor feugiat rutrum. Pellentesque vel neque accumsan, rutrum nulla in, facilisis lectus. Cras eleifend odio quam, a pellentesque nisi auctor quis. Nulla luctus pellentesque turpis, non volutpat felis accumsan ac. Ut at quam non purus finibus sodales nec non arcu. Vivamus sed sagittis eros. Etiam imperdiet erat eget lacus placerat, in mattis mauris hendrerit. Aliquam vitae feugiat magna, nec semper urna. Proin porttitor sagittis libero in placerat. Fusce mauris tellus, cursus et risus ut, venenatis rutrum orci. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus maximus nisl tortor, ac blandit tellus molestie eu. Mauris volutpat laoreet eros non tempus.

Nulla vitae ante vel urna cursus aliquet. Curabitur semper volutpat lobortis. Fusce et turpis eu quam gravida tempus a nec tortor. Mauris in semper elit. Maecenas congue diam mollis dolor luctus ultrices. Duis sed porttitor nunc, ut venenatis tortor. Praesent dictum lorem quis justo porttitor, quis iaculis turpis consequat. Donec vitae convallis ligula. Fusce laoreet lectus id nibh egestas, sit amet commodo nibh bibendum. Sed tempus velit vitae diam efficitur dapibus. Fusce eu nisi enim. Praesent vehicula fringilla tincidunt.

Donec et rhoncus sapien. Etiam ligula quam, rhoncus eu fermentum nec, pharetra a libero. Phasellus fringilla, augue et gravida molestie, urna erat congue nulla, nec suscipit nibh dui ac massa. In tincidunt suscipit purus. Sed sit amet ipsum sit amet tortor rhoncus pretium. Suspendisse et arcu semper, ullamcorper urna vitae, lacinia ligula. Suspendisse consequat in neque vitae malesuada. Pellentesque ut tristique quam. Nunc eu erat odio. Aenean erat erat, vehicula non consequat eget, tincidunt quis mi.

Nam commodo condimentum metus. Ut rutrum vulputate imperdiet. In eu sem eget libero semper consequat. Mauris accumsan nunc ut turpis feugiat dapibus. Sed aliquam purus volutpat tempor accumsan. Suspendisse placerat a metus quis laoreet. Suspendisse tristique interdum tortor et lacinia. In eu nisi quis arcu egestas ultricies eget sit amet magna. Morbi imperdiet et leo eget pharetra. Quisque hendrerit porta lacus sed eleifend. Quisque non fermentum nulla, sed gravida lacus. Donec pretium justo sit amet neque porttitor scelerisque. Mauris cursus pulvinar mi vitae cursus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos ', user_id: User.first.id, classroom_id: 3)
Note.create(title:"Test Note 10", content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus volutpat justo sed est tincidunt accumsan. Nam eget quam urna. Praesent lacinia odio metus, a venenatis orci porta sed. Mauris rutrum justo sit amet sem commodo faucibus. Suspendisse egestas eget est in posuere. Duis ac elit sed felis fringilla elementum. Ut a diam at arcu maximus iaculis. Nam placerat ante eu suscipit placerat. Vivamus cursus purus ipsum, ut facilisis lectus ullamcorper ac. Proin eget turpis non ligula placerat fringilla id a ante.

Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris scelerisque maximus dui, in rutrum magna mollis eget. Vivamus at massa at dolor feugiat rutrum. Pellentesque vel neque accumsan, rutrum nulla in, facilisis lectus. Cras eleifend odio quam, a pellentesque nisi auctor quis. Nulla luctus pellentesque turpis, non volutpat felis accumsan ac. Ut at quam non purus finibus sodales nec non arcu. Vivamus sed sagittis eros. Etiam imperdiet erat eget lacus placerat, in mattis mauris hendrerit. Aliquam vitae feugiat magna, nec semper urna. Proin porttitor sagittis libero in placerat. Fusce mauris tellus, cursus et risus ut, venenatis rutrum orci. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus maximus nisl tortor, ac blandit tellus molestie eu. Mauris volutpat laoreet eros non tempus.

Nulla vitae ante vel urna cursus aliquet. Curabitur semper volutpat lobortis. Fusce et turpis eu quam gravida tempus a nec tortor. Mauris in semper elit. Maecenas congue diam mollis dolor luctus ultrices. Duis sed porttitor nunc, ut venenatis tortor. Praesent dictum lorem quis justo porttitor, quis iaculis turpis consequat. Donec vitae convallis ligula. Fusce laoreet lectus id nibh egestas, sit amet commodo nibh bibendum. Sed tempus velit vitae diam efficitur dapibus. Fusce eu nisi enim. Praesent vehicula fringilla tincidunt.

Donec et rhoncus sapien. Etiam ligula quam, rhoncus eu fermentum nec, pharetra a libero. Phasellus fringilla, augue et gravida molestie, urna erat congue nulla, nec suscipit nibh dui ac massa. In tincidunt suscipit purus. Sed sit amet ipsum sit amet tortor rhoncus pretium. Suspendisse et arcu semper, ullamcorper urna vitae, lacinia ligula. Suspendisse consequat in neque vitae malesuada. Pellentesque ut tristique quam. Nunc eu erat odio. Aenean erat erat, vehicula non consequat eget, tincidunt quis mi.

Nam commodo condimentum metus. Ut rutrum vulputate imperdiet. In eu sem eget libero semper consequat. Mauris accumsan nunc ut turpis feugiat dapibus. Sed aliquam purus volutpat tempor accumsan. Suspendisse placerat a metus quis laoreet. Suspendisse tristique interdum tortor et lacinia. In eu nisi quis arcu egestas ultricies eget sit amet magna. Morbi imperdiet et leo eget pharetra. Quisque hendrerit porta lacus sed eleifend. Quisque non fermentum nulla, sed gravida lacus. Donec pretium justo sit amet neque porttitor scelerisque. Mauris cursus pulvinar mi vitae cursus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos ', user_id: User.first.id, classroom_id: 3)
Note.create(title:"Test Note 11", content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus volutpat justo sed est tincidunt accumsan. Nam eget quam urna. Praesent lacinia odio metus, a venenatis orci porta sed. Mauris rutrum justo sit amet sem commodo faucibus. Suspendisse egestas eget est in posuere. Duis ac elit sed felis fringilla elementum. Ut a diam at arcu maximus iaculis. Nam placerat ante eu suscipit placerat. Vivamus cursus purus ipsum, ut facilisis lectus ullamcorper ac. Proin eget turpis non ligula placerat fringilla id a ante.

Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris scelerisque maximus dui, in rutrum magna mollis eget. Vivamus at massa at dolor feugiat rutrum. Pellentesque vel neque accumsan, rutrum nulla in, facilisis lectus. Cras eleifend odio quam, a pellentesque nisi auctor quis. Nulla luctus pellentesque turpis, non volutpat felis accumsan ac. Ut at quam non purus finibus sodales nec non arcu. Vivamus sed sagittis eros. Etiam imperdiet erat eget lacus placerat, in mattis mauris hendrerit. Aliquam vitae feugiat magna, nec semper urna. Proin porttitor sagittis libero in placerat. Fusce mauris tellus, cursus et risus ut, venenatis rutrum orci. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus maximus nisl tortor, ac blandit tellus molestie eu. Mauris volutpat laoreet eros non tempus.

Nulla vitae ante vel urna cursus aliquet. Curabitur semper volutpat lobortis. Fusce et turpis eu quam gravida tempus a nec tortor. Mauris in semper elit. Maecenas congue diam mollis dolor luctus ultrices. Duis sed porttitor nunc, ut venenatis tortor. Praesent dictum lorem quis justo porttitor, quis iaculis turpis consequat. Donec vitae convallis ligula. Fusce laoreet lectus id nibh egestas, sit amet commodo nibh bibendum. Sed tempus velit vitae diam efficitur dapibus. Fusce eu nisi enim. Praesent vehicula fringilla tincidunt.

Donec et rhoncus sapien. Etiam ligula quam, rhoncus eu fermentum nec, pharetra a libero. Phasellus fringilla, augue et gravida molestie, urna erat congue nulla, nec suscipit nibh dui ac massa. In tincidunt suscipit purus. Sed sit amet ipsum sit amet tortor rhoncus pretium. Suspendisse et arcu semper, ullamcorper urna vitae, lacinia ligula. Suspendisse consequat in neque vitae malesuada. Pellentesque ut tristique quam. Nunc eu erat odio. Aenean erat erat, vehicula non consequat eget, tincidunt quis mi.

Nam commodo condimentum metus. Ut rutrum vulputate imperdiet. In eu sem eget libero semper consequat. Mauris accumsan nunc ut turpis feugiat dapibus. Sed aliquam purus volutpat tempor accumsan. Suspendisse placerat a metus quis laoreet. Suspendisse tristique interdum tortor et lacinia. In eu nisi quis arcu egestas ultricies eget sit amet magna. Morbi imperdiet et leo eget pharetra. Quisque hendrerit porta lacus sed eleifend. Quisque non fermentum nulla, sed gravida lacus. Donec pretium justo sit amet neque porttitor scelerisque. Mauris cursus pulvinar mi vitae cursus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos ', user_id: User.first.id, classroom_id: 3)
Note.create(title:"Test Note 12", content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus volutpat justo sed est tincidunt accumsan. Nam eget quam urna. Praesent lacinia odio metus, a venenatis orci porta sed. Mauris rutrum justo sit amet sem commodo faucibus. Suspendisse egestas eget est in posuere. Duis ac elit sed felis fringilla elementum. Ut a diam at arcu maximus iaculis. Nam placerat ante eu suscipit placerat. Vivamus cursus purus ipsum, ut facilisis lectus ullamcorper ac. Proin eget turpis non ligula placerat fringilla id a ante.

Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris scelerisque maximus dui, in rutrum magna mollis eget. Vivamus at massa at dolor feugiat rutrum. Pellentesque vel neque accumsan, rutrum nulla in, facilisis lectus. Cras eleifend odio quam, a pellentesque nisi auctor quis. Nulla luctus pellentesque turpis, non volutpat felis accumsan ac. Ut at quam non purus finibus sodales nec non arcu. Vivamus sed sagittis eros. Etiam imperdiet erat eget lacus placerat, in mattis mauris hendrerit. Aliquam vitae feugiat magna, nec semper urna. Proin porttitor sagittis libero in placerat. Fusce mauris tellus, cursus et risus ut, venenatis rutrum orci. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus maximus nisl tortor, ac blandit tellus molestie eu. Mauris volutpat laoreet eros non tempus.

Nulla vitae ante vel urna cursus aliquet. Curabitur semper volutpat lobortis. Fusce et turpis eu quam gravida tempus a nec tortor. Mauris in semper elit. Maecenas congue diam mollis dolor luctus ultrices. Duis sed porttitor nunc, ut venenatis tortor. Praesent dictum lorem quis justo porttitor, quis iaculis turpis consequat. Donec vitae convallis ligula. Fusce laoreet lectus id nibh egestas, sit amet commodo nibh bibendum. Sed tempus velit vitae diam efficitur dapibus. Fusce eu nisi enim. Praesent vehicula fringilla tincidunt.

Donec et rhoncus sapien. Etiam ligula quam, rhoncus eu fermentum nec, pharetra a libero. Phasellus fringilla, augue et gravida molestie, urna erat congue nulla, nec suscipit nibh dui ac massa. In tincidunt suscipit purus. Sed sit amet ipsum sit amet tortor rhoncus pretium. Suspendisse et arcu semper, ullamcorper urna vitae, lacinia ligula. Suspendisse consequat in neque vitae malesuada. Pellentesque ut tristique quam. Nunc eu erat odio. Aenean erat erat, vehicula non consequat eget, tincidunt quis mi.

Nam commodo condimentum metus. Ut rutrum vulputate imperdiet. In eu sem eget libero semper consequat. Mauris accumsan nunc ut turpis feugiat dapibus. Sed aliquam purus volutpat tempor accumsan. Suspendisse placerat a metus quis laoreet. Suspendisse tristique interdum tortor et lacinia. In eu nisi quis arcu egestas ultricies eget sit amet magna. Morbi imperdiet et leo eget pharetra. Quisque hendrerit porta lacus sed eleifend. Quisque non fermentum nulla, sed gravida lacus. Donec pretium justo sit amet neque porttitor scelerisque. Mauris cursus pulvinar mi vitae cursus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos ', user_id: User.first.id, classroom_id: 3)



Note.create(title:"Test Note 13", content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus volutpat justo sed est tincidunt accumsan. Nam eget quam urna. Praesent lacinia odio metus, a venenatis orci porta sed. Mauris rutrum justo sit amet sem commodo faucibus. Suspendisse egestas eget est in posuere. Duis ac elit sed felis fringilla elementum. Ut a diam at arcu maximus iaculis. Nam placerat ante eu suscipit placerat. Vivamus cursus purus ipsum, ut facilisis lectus ullamcorper ac. Proin eget turpis non ligula placerat fringilla id a ante.

Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris scelerisque maximus dui, in rutrum magna mollis eget. Vivamus at massa at dolor feugiat rutrum. Pellentesque vel neque accumsan, rutrum nulla in, facilisis lectus. Cras eleifend odio quam, a pellentesque nisi auctor quis. Nulla luctus pellentesque turpis, non volutpat felis accumsan ac. Ut at quam non purus finibus sodales nec non arcu. Vivamus sed sagittis eros. Etiam imperdiet erat eget lacus placerat, in mattis mauris hendrerit. Aliquam vitae feugiat magna, nec semper urna. Proin porttitor sagittis libero in placerat. Fusce mauris tellus, cursus et risus ut, venenatis rutrum orci. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus maximus nisl tortor, ac blandit tellus molestie eu. Mauris volutpat laoreet eros non tempus.

Nulla vitae ante vel urna cursus aliquet. Curabitur semper volutpat lobortis. Fusce et turpis eu quam gravida tempus a nec tortor. Mauris in semper elit. Maecenas congue diam mollis dolor luctus ultrices. Duis sed porttitor nunc, ut venenatis tortor. Praesent dictum lorem quis justo porttitor, quis iaculis turpis consequat. Donec vitae convallis ligula. Fusce laoreet lectus id nibh egestas, sit amet commodo nibh bibendum. Sed tempus velit vitae diam efficitur dapibus. Fusce eu nisi enim. Praesent vehicula fringilla tincidunt.

Donec et rhoncus sapien. Etiam ligula quam, rhoncus eu fermentum nec, pharetra a libero. Phasellus fringilla, augue et gravida molestie, urna erat congue nulla, nec suscipit nibh dui ac massa. In tincidunt suscipit purus. Sed sit amet ipsum sit amet tortor rhoncus pretium. Suspendisse et arcu semper, ullamcorper urna vitae, lacinia ligula. Suspendisse consequat in neque vitae malesuada. Pellentesque ut tristique quam. Nunc eu erat odio. Aenean erat erat, vehicula non consequat eget, tincidunt quis mi.

Nam commodo condimentum metus. Ut rutrum vulputate imperdiet. In eu sem eget libero semper consequat. Mauris accumsan nunc ut turpis feugiat dapibus. Sed aliquam purus volutpat tempor accumsan. Suspendisse placerat a metus quis laoreet. Suspendisse tristique interdum tortor et lacinia. In eu nisi quis arcu egestas ultricies eget sit amet magna. Morbi imperdiet et leo eget pharetra. Quisque hendrerit porta lacus sed eleifend. Quisque non fermentum nulla, sed gravida lacus. Donec pretium justo sit amet neque porttitor scelerisque. Mauris cursus pulvinar mi vitae cursus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos ', user_id: User.second.id, classroom_id: 2)
Note.create(title:"Test Note 14", content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus volutpat justo sed est tincidunt accumsan. Nam eget quam urna. Praesent lacinia odio metus, a venenatis orci porta sed. Mauris rutrum justo sit amet sem commodo faucibus. Suspendisse egestas eget est in posuere. Duis ac elit sed felis fringilla elementum. Ut a diam at arcu maximus iaculis. Nam placerat ante eu suscipit placerat. Vivamus cursus purus ipsum, ut facilisis lectus ullamcorper ac. Proin eget turpis non ligula placerat fringilla id a ante.

Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris scelerisque maximus dui, in rutrum magna mollis eget. Vivamus at massa at dolor feugiat rutrum. Pellentesque vel neque accumsan, rutrum nulla in, facilisis lectus. Cras eleifend odio quam, a pellentesque nisi auctor quis. Nulla luctus pellentesque turpis, non volutpat felis accumsan ac. Ut at quam non purus finibus sodales nec non arcu. Vivamus sed sagittis eros. Etiam imperdiet erat eget lacus placerat, in mattis mauris hendrerit. Aliquam vitae feugiat magna, nec semper urna. Proin porttitor sagittis libero in placerat. Fusce mauris tellus, cursus et risus ut, venenatis rutrum orci. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus maximus nisl tortor, ac blandit tellus molestie eu. Mauris volutpat laoreet eros non tempus.

Nulla vitae ante vel urna cursus aliquet. Curabitur semper volutpat lobortis. Fusce et turpis eu quam gravida tempus a nec tortor. Mauris in semper elit. Maecenas congue diam mollis dolor luctus ultrices. Duis sed porttitor nunc, ut venenatis tortor. Praesent dictum lorem quis justo porttitor, quis iaculis turpis consequat. Donec vitae convallis ligula. Fusce laoreet lectus id nibh egestas, sit amet commodo nibh bibendum. Sed tempus velit vitae diam efficitur dapibus. Fusce eu nisi enim. Praesent vehicula fringilla tincidunt.

Donec et rhoncus sapien. Etiam ligula quam, rhoncus eu fermentum nec, pharetra a libero. Phasellus fringilla, augue et gravida molestie, urna erat congue nulla, nec suscipit nibh dui ac massa. In tincidunt suscipit purus. Sed sit amet ipsum sit amet tortor rhoncus pretium. Suspendisse et arcu semper, ullamcorper urna vitae, lacinia ligula. Suspendisse consequat in neque vitae malesuada. Pellentesque ut tristique quam. Nunc eu erat odio. Aenean erat erat, vehicula non consequat eget, tincidunt quis mi.

Nam commodo condimentum metus. Ut rutrum vulputate imperdiet. In eu sem eget libero semper consequat. Mauris accumsan nunc ut turpis feugiat dapibus. Sed aliquam purus volutpat tempor accumsan. Suspendisse placerat a metus quis laoreet. Suspendisse tristique interdum tortor et lacinia. In eu nisi quis arcu egestas ultricies eget sit amet magna. Morbi imperdiet et leo eget pharetra. Quisque hendrerit porta lacus sed eleifend. Quisque non fermentum nulla, sed gravida lacus. Donec pretium justo sit amet neque porttitor scelerisque. Mauris cursus pulvinar mi vitae cursus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos ', user_id: User.second.id, classroom_id: 2)
Note.create(title:"Test Note 15", content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus volutpat justo sed est tincidunt accumsan. Nam eget quam urna. Praesent lacinia odio metus, a venenatis orci porta sed. Mauris rutrum justo sit amet sem commodo faucibus. Suspendisse egestas eget est in posuere. Duis ac elit sed felis fringilla elementum. Ut a diam at arcu maximus iaculis. Nam placerat ante eu suscipit placerat. Vivamus cursus purus ipsum, ut facilisis lectus ullamcorper ac. Proin eget turpis non ligula placerat fringilla id a ante.

Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris scelerisque maximus dui, in rutrum magna mollis eget. Vivamus at massa at dolor feugiat rutrum. Pellentesque vel neque accumsan, rutrum nulla in, facilisis lectus. Cras eleifend odio quam, a pellentesque nisi auctor quis. Nulla luctus pellentesque turpis, non volutpat felis accumsan ac. Ut at quam non purus finibus sodales nec non arcu. Vivamus sed sagittis eros. Etiam imperdiet erat eget lacus placerat, in mattis mauris hendrerit. Aliquam vitae feugiat magna, nec semper urna. Proin porttitor sagittis libero in placerat. Fusce mauris tellus, cursus et risus ut, venenatis rutrum orci. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus maximus nisl tortor, ac blandit tellus molestie eu. Mauris volutpat laoreet eros non tempus.

Nulla vitae ante vel urna cursus aliquet. Curabitur semper volutpat lobortis. Fusce et turpis eu quam gravida tempus a nec tortor. Mauris in semper elit. Maecenas congue diam mollis dolor luctus ultrices. Duis sed porttitor nunc, ut venenatis tortor. Praesent dictum lorem quis justo porttitor, quis iaculis turpis consequat. Donec vitae convallis ligula. Fusce laoreet lectus id nibh egestas, sit amet commodo nibh bibendum. Sed tempus velit vitae diam efficitur dapibus. Fusce eu nisi enim. Praesent vehicula fringilla tincidunt.

Donec et rhoncus sapien. Etiam ligula quam, rhoncus eu fermentum nec, pharetra a libero. Phasellus fringilla, augue et gravida molestie, urna erat congue nulla, nec suscipit nibh dui ac massa. In tincidunt suscipit purus. Sed sit amet ipsum sit amet tortor rhoncus pretium. Suspendisse et arcu semper, ullamcorper urna vitae, lacinia ligula. Suspendisse consequat in neque vitae malesuada. Pellentesque ut tristique quam. Nunc eu erat odio. Aenean erat erat, vehicula non consequat eget, tincidunt quis mi.

Nam commodo condimentum metus. Ut rutrum vulputate imperdiet. In eu sem eget libero semper consequat. Mauris accumsan nunc ut turpis feugiat dapibus. Sed aliquam purus volutpat tempor accumsan. Suspendisse placerat a metus quis laoreet. Suspendisse tristique interdum tortor et lacinia. In eu nisi quis arcu egestas ultricies eget sit amet magna. Morbi imperdiet et leo eget pharetra. Quisque hendrerit porta lacus sed eleifend. Quisque non fermentum nulla, sed gravida lacus. Donec pretium justo sit amet neque porttitor scelerisque. Mauris cursus pulvinar mi vitae cursus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos ', user_id: User.second.id, classroom_id: 2)
Note.create(title:"Test Note 16", content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus volutpat justo sed est tincidunt accumsan. Nam eget quam urna. Praesent lacinia odio metus, a venenatis orci porta sed. Mauris rutrum justo sit amet sem commodo faucibus. Suspendisse egestas eget est in posuere. Duis ac elit sed felis fringilla elementum. Ut a diam at arcu maximus iaculis. Nam placerat ante eu suscipit placerat. Vivamus cursus purus ipsum, ut facilisis lectus ullamcorper ac. Proin eget turpis non ligula placerat fringilla id a ante.

Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris scelerisque maximus dui, in rutrum magna mollis eget. Vivamus at massa at dolor feugiat rutrum. Pellentesque vel neque accumsan, rutrum nulla in, facilisis lectus. Cras eleifend odio quam, a pellentesque nisi auctor quis. Nulla luctus pellentesque turpis, non volutpat felis accumsan ac. Ut at quam non purus finibus sodales nec non arcu. Vivamus sed sagittis eros. Etiam imperdiet erat eget lacus placerat, in mattis mauris hendrerit. Aliquam vitae feugiat magna, nec semper urna. Proin porttitor sagittis libero in placerat. Fusce mauris tellus, cursus et risus ut, venenatis rutrum orci. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus maximus nisl tortor, ac blandit tellus molestie eu. Mauris volutpat laoreet eros non tempus.

Nulla vitae ante vel urna cursus aliquet. Curabitur semper volutpat lobortis. Fusce et turpis eu quam gravida tempus a nec tortor. Mauris in semper elit. Maecenas congue diam mollis dolor luctus ultrices. Duis sed porttitor nunc, ut venenatis tortor. Praesent dictum lorem quis justo porttitor, quis iaculis turpis consequat. Donec vitae convallis ligula. Fusce laoreet lectus id nibh egestas, sit amet commodo nibh bibendum. Sed tempus velit vitae diam efficitur dapibus. Fusce eu nisi enim. Praesent vehicula fringilla tincidunt.

Donec et rhoncus sapien. Etiam ligula quam, rhoncus eu fermentum nec, pharetra a libero. Phasellus fringilla, augue et gravida molestie, urna erat congue nulla, nec suscipit nibh dui ac massa. In tincidunt suscipit purus. Sed sit amet ipsum sit amet tortor rhoncus pretium. Suspendisse et arcu semper, ullamcorper urna vitae, lacinia ligula. Suspendisse consequat in neque vitae malesuada. Pellentesque ut tristique quam. Nunc eu erat odio. Aenean erat erat, vehicula non consequat eget, tincidunt quis mi.

Nam commodo condimentum metus. Ut rutrum vulputate imperdiet. In eu sem eget libero semper consequat. Mauris accumsan nunc ut turpis feugiat dapibus. Sed aliquam purus volutpat tempor accumsan. Suspendisse placerat a metus quis laoreet. Suspendisse tristique interdum tortor et lacinia. In eu nisi quis arcu egestas ultricies eget sit amet magna. Morbi imperdiet et leo eget pharetra. Quisque hendrerit porta lacus sed eleifend. Quisque non fermentum nulla, sed gravida lacus. Donec pretium justo sit amet neque porttitor scelerisque. Mauris cursus pulvinar mi vitae cursus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos ', user_id: User.second.id, classroom_id: 2)

Note.create(title:"Test Note 17", content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus volutpat justo sed est tincidunt accumsan. Nam eget quam urna. Praesent lacinia odio metus, a venenatis orci porta sed. Mauris rutrum justo sit amet sem commodo faucibus. Suspendisse egestas eget est in posuere. Duis ac elit sed felis fringilla elementum. Ut a diam at arcu maximus iaculis. Nam placerat ante eu suscipit placerat. Vivamus cursus purus ipsum, ut facilisis lectus ullamcorper ac. Proin eget turpis non ligula placerat fringilla id a ante.

Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris scelerisque maximus dui, in rutrum magna mollis eget. Vivamus at massa at dolor feugiat rutrum. Pellentesque vel neque accumsan, rutrum nulla in, facilisis lectus. Cras eleifend odio quam, a pellentesque nisi auctor quis. Nulla luctus pellentesque turpis, non volutpat felis accumsan ac. Ut at quam non purus finibus sodales nec non arcu. Vivamus sed sagittis eros. Etiam imperdiet erat eget lacus placerat, in mattis mauris hendrerit. Aliquam vitae feugiat magna, nec semper urna. Proin porttitor sagittis libero in placerat. Fusce mauris tellus, cursus et risus ut, venenatis rutrum orci. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus maximus nisl tortor, ac blandit tellus molestie eu. Mauris volutpat laoreet eros non tempus.

Nulla vitae ante vel urna cursus aliquet. Curabitur semper volutpat lobortis. Fusce et turpis eu quam gravida tempus a nec tortor. Mauris in semper elit. Maecenas congue diam mollis dolor luctus ultrices. Duis sed porttitor nunc, ut venenatis tortor. Praesent dictum lorem quis justo porttitor, quis iaculis turpis consequat. Donec vitae convallis ligula. Fusce laoreet lectus id nibh egestas, sit amet commodo nibh bibendum. Sed tempus velit vitae diam efficitur dapibus. Fusce eu nisi enim. Praesent vehicula fringilla tincidunt.

Donec et rhoncus sapien. Etiam ligula quam, rhoncus eu fermentum nec, pharetra a libero. Phasellus fringilla, augue et gravida molestie, urna erat congue nulla, nec suscipit nibh dui ac massa. In tincidunt suscipit purus. Sed sit amet ipsum sit amet tortor rhoncus pretium. Suspendisse et arcu semper, ullamcorper urna vitae, lacinia ligula. Suspendisse consequat in neque vitae malesuada. Pellentesque ut tristique quam. Nunc eu erat odio. Aenean erat erat, vehicula non consequat eget, tincidunt quis mi.

Nam commodo condimentum metus. Ut rutrum vulputate imperdiet. In eu sem eget libero semper consequat. Mauris accumsan nunc ut turpis feugiat dapibus. Sed aliquam purus volutpat tempor accumsan. Suspendisse placerat a metus quis laoreet. Suspendisse tristique interdum tortor et lacinia. In eu nisi quis arcu egestas ultricies eget sit amet magna. Morbi imperdiet et leo eget pharetra. Quisque hendrerit porta lacus sed eleifend. Quisque non fermentum nulla, sed gravida lacus. Donec pretium justo sit amet neque porttitor scelerisque. Mauris cursus pulvinar mi vitae cursus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos ', user_id: User.second.id, classroom_id: 3)
Note.create(title:"Test Note 18", content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus volutpat justo sed est tincidunt accumsan. Nam eget quam urna. Praesent lacinia odio metus, a venenatis orci porta sed. Mauris rutrum justo sit amet sem commodo faucibus. Suspendisse egestas eget est in posuere. Duis ac elit sed felis fringilla elementum. Ut a diam at arcu maximus iaculis. Nam placerat ante eu suscipit placerat. Vivamus cursus purus ipsum, ut facilisis lectus ullamcorper ac. Proin eget turpis non ligula placerat fringilla id a ante.

Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris scelerisque maximus dui, in rutrum magna mollis eget. Vivamus at massa at dolor feugiat rutrum. Pellentesque vel neque accumsan, rutrum nulla in, facilisis lectus. Cras eleifend odio quam, a pellentesque nisi auctor quis. Nulla luctus pellentesque turpis, non volutpat felis accumsan ac. Ut at quam non purus finibus sodales nec non arcu. Vivamus sed sagittis eros. Etiam imperdiet erat eget lacus placerat, in mattis mauris hendrerit. Aliquam vitae feugiat magna, nec semper urna. Proin porttitor sagittis libero in placerat. Fusce mauris tellus, cursus et risus ut, venenatis rutrum orci. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus maximus nisl tortor, ac blandit tellus molestie eu. Mauris volutpat laoreet eros non tempus.

Nulla vitae ante vel urna cursus aliquet. Curabitur semper volutpat lobortis. Fusce et turpis eu quam gravida tempus a nec tortor. Mauris in semper elit. Maecenas congue diam mollis dolor luctus ultrices. Duis sed porttitor nunc, ut venenatis tortor. Praesent dictum lorem quis justo porttitor, quis iaculis turpis consequat. Donec vitae convallis ligula. Fusce laoreet lectus id nibh egestas, sit amet commodo nibh bibendum. Sed tempus velit vitae diam efficitur dapibus. Fusce eu nisi enim. Praesent vehicula fringilla tincidunt.

Donec et rhoncus sapien. Etiam ligula quam, rhoncus eu fermentum nec, pharetra a libero. Phasellus fringilla, augue et gravida molestie, urna erat congue nulla, nec suscipit nibh dui ac massa. In tincidunt suscipit purus. Sed sit amet ipsum sit amet tortor rhoncus pretium. Suspendisse et arcu semper, ullamcorper urna vitae, lacinia ligula. Suspendisse consequat in neque vitae malesuada. Pellentesque ut tristique quam. Nunc eu erat odio. Aenean erat erat, vehicula non consequat eget, tincidunt quis mi.

Nam commodo condimentum metus. Ut rutrum vulputate imperdiet. In eu sem eget libero semper consequat. Mauris accumsan nunc ut turpis feugiat dapibus. Sed aliquam purus volutpat tempor accumsan. Suspendisse placerat a metus quis laoreet. Suspendisse tristique interdum tortor et lacinia. In eu nisi quis arcu egestas ultricies eget sit amet magna. Morbi imperdiet et leo eget pharetra. Quisque hendrerit porta lacus sed eleifend. Quisque non fermentum nulla, sed gravida lacus. Donec pretium justo sit amet neque porttitor scelerisque. Mauris cursus pulvinar mi vitae cursus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos ', user_id: User.second.id, classroom_id: 3)
Note.create(title:"Test Note 19", content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus volutpat justo sed est tincidunt accumsan. Nam eget quam urna. Praesent lacinia odio metus, a venenatis orci porta sed. Mauris rutrum justo sit amet sem commodo faucibus. Suspendisse egestas eget est in posuere. Duis ac elit sed felis fringilla elementum. Ut a diam at arcu maximus iaculis. Nam placerat ante eu suscipit placerat. Vivamus cursus purus ipsum, ut facilisis lectus ullamcorper ac. Proin eget turpis non ligula placerat fringilla id a ante.

Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris scelerisque maximus dui, in rutrum magna mollis eget. Vivamus at massa at dolor feugiat rutrum. Pellentesque vel neque accumsan, rutrum nulla in, facilisis lectus. Cras eleifend odio quam, a pellentesque nisi auctor quis. Nulla luctus pellentesque turpis, non volutpat felis accumsan ac. Ut at quam non purus finibus sodales nec non arcu. Vivamus sed sagittis eros. Etiam imperdiet erat eget lacus placerat, in mattis mauris hendrerit. Aliquam vitae feugiat magna, nec semper urna. Proin porttitor sagittis libero in placerat. Fusce mauris tellus, cursus et risus ut, venenatis rutrum orci. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus maximus nisl tortor, ac blandit tellus molestie eu. Mauris volutpat laoreet eros non tempus.

Nulla vitae ante vel urna cursus aliquet. Curabitur semper volutpat lobortis. Fusce et turpis eu quam gravida tempus a nec tortor. Mauris in semper elit. Maecenas congue diam mollis dolor luctus ultrices. Duis sed porttitor nunc, ut venenatis tortor. Praesent dictum lorem quis justo porttitor, quis iaculis turpis consequat. Donec vitae convallis ligula. Fusce laoreet lectus id nibh egestas, sit amet commodo nibh bibendum. Sed tempus velit vitae diam efficitur dapibus. Fusce eu nisi enim. Praesent vehicula fringilla tincidunt.

Donec et rhoncus sapien. Etiam ligula quam, rhoncus eu fermentum nec, pharetra a libero. Phasellus fringilla, augue et gravida molestie, urna erat congue nulla, nec suscipit nibh dui ac massa. In tincidunt suscipit purus. Sed sit amet ipsum sit amet tortor rhoncus pretium. Suspendisse et arcu semper, ullamcorper urna vitae, lacinia ligula. Suspendisse consequat in neque vitae malesuada. Pellentesque ut tristique quam. Nunc eu erat odio. Aenean erat erat, vehicula non consequat eget, tincidunt quis mi.

Nam commodo condimentum metus. Ut rutrum vulputate imperdiet. In eu sem eget libero semper consequat. Mauris accumsan nunc ut turpis feugiat dapibus. Sed aliquam purus volutpat tempor accumsan. Suspendisse placerat a metus quis laoreet. Suspendisse tristique interdum tortor et lacinia. In eu nisi quis arcu egestas ultricies eget sit amet magna. Morbi imperdiet et leo eget pharetra. Quisque hendrerit porta lacus sed eleifend. Quisque non fermentum nulla, sed gravida lacus. Donec pretium justo sit amet neque porttitor scelerisque. Mauris cursus pulvinar mi vitae cursus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos ', user_id: User.second.id, classroom_id: 3)
Note.create(title:"Test Note 20", content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus volutpat justo sed est tincidunt accumsan. Nam eget quam urna. Praesent lacinia odio metus, a venenatis orci porta sed. Mauris rutrum justo sit amet sem commodo faucibus. Suspendisse egestas eget est in posuere. Duis ac elit sed felis fringilla elementum. Ut a diam at arcu maximus iaculis. Nam placerat ante eu suscipit placerat. Vivamus cursus purus ipsum, ut facilisis lectus ullamcorper ac. Proin eget turpis non ligula placerat fringilla id a ante.

Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris scelerisque maximus dui, in rutrum magna mollis eget. Vivamus at massa at dolor feugiat rutrum. Pellentesque vel neque accumsan, rutrum nulla in, facilisis lectus. Cras eleifend odio quam, a pellentesque nisi auctor quis. Nulla luctus pellentesque turpis, non volutpat felis accumsan ac. Ut at quam non purus finibus sodales nec non arcu. Vivamus sed sagittis eros. Etiam imperdiet erat eget lacus placerat, in mattis mauris hendrerit. Aliquam vitae feugiat magna, nec semper urna. Proin porttitor sagittis libero in placerat. Fusce mauris tellus, cursus et risus ut, venenatis rutrum orci. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus maximus nisl tortor, ac blandit tellus molestie eu. Mauris volutpat laoreet eros non tempus.

Nulla vitae ante vel urna cursus aliquet. Curabitur semper volutpat lobortis. Fusce et turpis eu quam gravida tempus a nec tortor. Mauris in semper elit. Maecenas congue diam mollis dolor luctus ultrices. Duis sed porttitor nunc, ut venenatis tortor. Praesent dictum lorem quis justo porttitor, quis iaculis turpis consequat. Donec vitae convallis ligula. Fusce laoreet lectus id nibh egestas, sit amet commodo nibh bibendum. Sed tempus velit vitae diam efficitur dapibus. Fusce eu nisi enim. Praesent vehicula fringilla tincidunt.

Donec et rhoncus sapien. Etiam ligula quam, rhoncus eu fermentum nec, pharetra a libero. Phasellus fringilla, augue et gravida molestie, urna erat congue nulla, nec suscipit nibh dui ac massa. In tincidunt suscipit purus. Sed sit amet ipsum sit amet tortor rhoncus pretium. Suspendisse et arcu semper, ullamcorper urna vitae, lacinia ligula. Suspendisse consequat in neque vitae malesuada. Pellentesque ut tristique quam. Nunc eu erat odio. Aenean erat erat, vehicula non consequat eget, tincidunt quis mi.

Nam commodo condimentum metus. Ut rutrum vulputate imperdiet. In eu sem eget libero semper consequat. Mauris accumsan nunc ut turpis feugiat dapibus. Sed aliquam purus volutpat tempor accumsan. Suspendisse placerat a metus quis laoreet. Suspendisse tristique interdum tortor et lacinia. In eu nisi quis arcu egestas ultricies eget sit amet magna. Morbi imperdiet et leo eget pharetra. Quisque hendrerit porta lacus sed eleifend. Quisque non fermentum nulla, sed gravida lacus. Donec pretium justo sit amet neque porttitor scelerisque. Mauris cursus pulvinar mi vitae cursus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos ', user_id: User.second.id, classroom_id: 3)
